#!/bin/bash
apt install -y curl

ID=openmediavault
URI_KEY='https://packages.openmediavault.org/public/archive.key'
PATH_FILE_SIGNED=/usr/share/keyrings/$ID-archive-keyring.gpg
PATH_FILE_SOURCE=/etc/apt/sources.list.d/$ID-sources.list


if [ ! -e $PATH_FILE_SOURCE ];
  then
  echo
  echo "[ Repositório ]: Configurando ..."

cat > $PATH_FILE_SOURCE << EOF
deb [signed-by=$PATH_FILE_SIGNED] http://packages.openmediavault.org/public/ sandworm main
deb [signed-by=$PATH_FILE_SIGNED] https://openmediavault.github.io/packages/ sandworm main
EOF

wget --quiet --output-document=- $URI_KEY | gpg --dearmor --yes --output $PATH_FILE_SIGNED > /dev/null
sleep 2

  echo "[ Repositório ]: Configurado!"
  echo
  echo "[ Repositório ]: Atualizando..."
  apt update -qq 2>&1 | grep "E:"
  apt upgrade -qqy 2>&1 | grep "E:"
  systemctl daemon-reload 2>&1 | grep "E:"
  apt --fix-broken -qq install 2>&1 | grep "E:"
  echo "[ Repositório ]: OK!"
  echo
fi
sleep 2
